### ISSUE TITLE
Setup Kanban Board

### ISSUE THREAD

**Issue by rubydevi** [rubydevi/food-recipe#11]
### Description
We have created tasks on our [Kanban board](https://github.com/rubydevi/food-recipe/projects/1) based on the [project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md).

**Team of 2 members:**
@rubydevi : Student A
@kit0-0 : Student B

**Comment by AbelG101** [comment]
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzFmY2U0ZTkwMmM3ZTM5MDBkNjhhZjk0MjI0OTU3MGNjYjMyMmRhOCZjdD1n/M1fddM48g9084bJMEX/giphy.gif)


# Hi @rubydevi & @kit0-0 👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Proper kanban template is used ✔
- Each card is assigned a team member ✔
- Tasks are distributed fairly ✔

## Required Changes ♻️
- [ ] I can see you've distributed the requirement for following the wireframe layout into separate cards which is good. However, I have a suggestion to improve your implementation. It would be beneficial to add an additional card specifically for the requirement "Personalize the rest of the design including colors, typographies, spacings, etc." This way, you can ensure that you won't overlook this important aspect of the design.
- Here's the project requirement as a reminder:
  ![image](https://github.com/rubydevi/food-recipe/assets/104968236/f4f55de1-4365-4a07-86a1-6d54eb0bda7e)



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @rubydevi and @kit0-0,

✔️ Tasks are complete and well-assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rubydevi** [comment]
Thanks @AbelG101 and @TedLivist for the review 😄
